spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 123456Qw
  jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true